// <auto-generated />
namespace MinhXuShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddErrorTable_FixColumnMesaageName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddErrorTable_FixColumnMesaageName));
        
        string IMigrationMetadata.Id
        {
            get { return "201607110509308_AddErrorTable_FixColumnMesaageName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
